global:
  scrape_interval: 5s 
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']