"""ajout champ test

Revision ID: 2063719ce1a4
Revises: e35c04f6187a
Create Date: 2025-06-19 15:13:45.149540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2063719ce1a4'
down_revision: Union[str, Sequence[str], None] = 'e35c04f6187a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'test')
    # ### end Alembic commands ###
