"""ajout champ test

Revision ID: de22d321874a
Revises: 2063719ce1a4
Create Date: 2025-06-19 15:16:09.809296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de22d321874a'
down_revision: Union[str, Sequence[str], None] = '2063719ce1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('test', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
