name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      
      - uses: actions/checkout@v3

      
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      
      - name: Lint with flake8
        run: |
          flake8 .

      
      - name: Build the Docker Image
        run: |
          docker compose --build

      
      - name: Run tests
        run: |
          docker run SAS_IA pytest

      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push the Docker image
        run: docker push SAS_IA

      - name: Send Discord notification (success)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \-X POST \-d '{"content": "✅ Déploiement terminé avec succès sur le serveur !"}' \${{ secrets.DISCORD_WEBHOOK }}

      
      - name: Send Discord notification (failure)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \-X POST \-d '{"content": "❌ Le déploiement CI/CD a échoué. Vérifie les logs."}' \${{ secrets.DISCORD_WEBHOOK }}
